### PR TITLE
Add support for FHIRPath expression-based, relative min and max date extensions

### PR DESCRIPTION
**Pull request by Supereg**
# Add support for FHIRPath expression-based, relative min and max date extensions

## :recycle: Current situation & Problem
Currently, with `date` questionnaire items, FHIR only supports exact min and max date values (e.g., exact date like 2024-04-14). However, as it is typical with, e.g., a date of birth picker, you want to restrict the max date relative to the current date (e.g., no value larger than today). Equally, specifying a min value that is relative to the current time might be desirable.

The Phoenix builder currently supports specifying such relative date ranges using FHIRPath expressions. This looks something like `today() + 3 months` or just `today()`. See [FHIRPath](https://hl7.org/fhirpath)  and [Current date and time functions](https://hl7.org/fhirpath/#current-date-and-time-functions).

This PR adds functionality for these expressions, implementing a parsers for the [FHIRPath Grammar](https://github.com/HL7/FHIRPath/blob/767f55a6f572419679cc37dfe9477e5465f86014/spec/2019May/fhirpath.g4)  using  [Antlr4](https://github.com/antlr/antlr4). It uses the generated syntax tree parser and implements a just in time evaluation for date expressions. All these operations are implemented in the internal `FHIRPathParser` target.

Consequentially, we integrate that with the ResearchKitOnFHIR conversion logic to consider the extensions from phoenix and parse the respective expressions.

## :gear: Release Notes 
* Added parser for FHIRPath grammar
* Add support for FHIRPath Data and DateTime expressions as min and max values for a `date` and `dateTime` questionnaire items.

## :books: Documentation
Documentation was added for all new infrastructure.

## :white_check_mark: Testing
Unit tests were added to verify the implementation for the date expression evaluation.

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Supereg** [comment]
The generated parser dramatically reduces our code coverage. Not sure if it makes sense to exclude it somehow from the codecov report?

**Comment by vishnuravi** [comment]
> The generated parser dramatically reduces our code coverage. Not sure if it makes sense to exclude it somehow from the codecov report?

This is incredible work @Supereg! :rocket:

Perhaps it makes sense to make the `FHIRPathParser` into a separate Swift package? This would not only address the code coverage issue, but also make it easier to use for other use cases beyond ResearchKit surveys, and could be expanded beyond date validation in the future.

**Review by vishnuravi — APPROVED** [review]

**Comment by Supereg** [comment]
> Perhaps it makes sense to make the FHIRPathParser into a separate Swift package or part of [SpeziFHIR](https://github.com/StanfordSpezi/SpeziFHIR)? This would not only address the code coverage issue, but also make it easier to use for other use cases beyond ResearchKit surveys, and could be expanded beyond date expressions in the near future.

As discussed, I think that would be a great step forward to eventually branch it out into a SpeziFHIR package. However, this would probably require a bit more work building a proper abstract syntax tree (AST) around the current syntax tree generated by Antlr. So for now, let's leave it as an internal target that just drives some of our features 🚀

**Comment by vishnuravi** [comment]
> > Perhaps it makes sense to make the FHIRPathParser into a separate Swift package or part of [SpeziFHIR](https://github.com/StanfordSpezi/SpeziFHIR)? This would not only address the code coverage issue, but also make it easier to use for other use cases beyond ResearchKit surveys, and could be expanded beyond date expressions in the near future.
> 
> As discussed, I think that would be a great step forward to eventually branch it out into a SpeziFHIR package. However, this would probably require a bit more work building a proper abstract syntax tree (AST) around the current syntax tree generated by Antlr. So for now, let's leave it as an internal target that just drives some of our features 🚀

Sounds good to me!

**Pull request merged**
